import { Platform, StatusBar, StyleSheet } from "react-native";

export const colors = {
  background: "#f4f7fa",
  text: "#26262a",
  muted: "#8b8e96",
  border: "#edf0f3",
  softBorder: "#f2f3f5",
  primary: "#ffd83d",
  primarySoft: "#fff5bd",
  accent: "#2f2f33",
  accentSoft: "#f6f6f6",
  danger: "#e45656",
  success: "#13b981",
  warning: "#ffb020",
  surface: "#fff"
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background, paddingTop: Platform.OS === "android" ? StatusBar.currentHeight ?? 0 : 0 },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, backgroundColor: colors.background },
  flex: { flex: 1 },
  header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 12, backgroundColor: colors.primary },
  title: { fontSize: 26, fontWeight: "900", color: colors.text, textAlign: "center" },
  subtitle: { marginTop: 4, color: "#5f571f", textAlign: "center" },
  content: { flex: 1 },
  contentBody: { padding: 16, paddingBottom: 28 },
  hero: { backgroundColor: colors.primary, borderRadius: 0, paddingHorizontal: 20, paddingTop: 6, paddingBottom: 22, marginHorizontal: -16, marginTop: -16, marginBottom: 12 },
  heroLabel: { color: "#6f6423", fontSize: 14, fontWeight: "800" },
  heroAmount: { color: colors.text, fontSize: 42, fontWeight: "900", marginVertical: 8 },
  heroHint: { color: "#5f571f", fontWeight: "800" },
  monthSummaryRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12 },
  monthBlock: { flex: 1 },
  monthYear: { color: "#786d25", fontSize: 16, fontWeight: "800" },
  monthText: { color: colors.text, fontSize: 42, fontWeight: "900" },
  monthUnit: { fontSize: 22, fontWeight: "800" },
  summaryBlock: { flex: 1, alignItems: "center" },
  summaryLabel: { color: "#786d25", fontSize: 15, fontWeight: "800", marginBottom: 8 },
  summaryValue: { color: colors.text, fontSize: 24, fontWeight: "500" },
  monthSwitcher: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 16, gap: 8 },
  monthSwitchText: { color: colors.text, fontWeight: "900", backgroundColor: "rgba(255,255,255,0.35)", paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999 },
  monthSwitchTextDisabled: { color: "rgba(38,38,42,0.32)", backgroundColor: "rgba(255,255,255,0.18)" },
  monthCompareText: { flex: 1, color: "#5f571f", fontSize: 12, fontWeight: "800", textAlign: "center" },
  monthPicker: { marginTop: 16, backgroundColor: "rgba(255,255,255,0.35)", borderRadius: 16, padding: 12 },
  monthPickerHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  monthPickerYear: { color: colors.text, fontSize: 18, fontWeight: "900" },
  currentMonthButton: { alignSelf: "center", color: colors.text, fontWeight: "900", backgroundColor: colors.surface, paddingHorizontal: 18, paddingVertical: 8, borderRadius: 999, marginBottom: 10 },
  floatingCurrentMonthButton: {
    position: "absolute",
    alignSelf: "center",
    bottom: Platform.OS === "ios" ? 132 : 120,
    zIndex: 10,
    color: colors.text,
    fontWeight: "900",
    backgroundColor: colors.surface,
    paddingHorizontal: 22,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.softBorder
  },
  monthGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 8 },
  monthGridItem: { width: "23.5%", textAlign: "center", color: colors.text, fontWeight: "900", paddingVertical: 10, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.35)" },
  monthGridItemActive: { backgroundColor: colors.text, color: colors.surface },
  monthGridItemDisabled: { color: "rgba(38,38,42,0.28)", backgroundColor: "rgba(255,255,255,0.18)" },
  dayHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 14, marginBottom: 8 },
  dayHeaderText: { color: colors.muted, fontSize: 15, fontWeight: "800" },
  dayGroupHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 16, marginBottom: 8 },
  dayGroupTitle: { color: colors.text, fontSize: 18, fontWeight: "900" },
  dayGroupTotals: { alignItems: "flex-end", gap: 2 },
  dayGroupAmount: { color: colors.muted, fontSize: 14, fontWeight: "800" },
  dayGroupIncome: { color: colors.success, fontSize: 13, fontWeight: "800" },
  grid: { flexDirection: "row", gap: 10 },
  metric: { flex: 1, backgroundColor: colors.surface, borderRadius: 10, padding: 14, borderWidth: 1, borderColor: colors.softBorder },
  metricLabel: { color: colors.muted, marginBottom: 6 },
  metricValue: { color: colors.text, fontSize: 18, fontWeight: "900" },
  sectionTitle: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 22, marginBottom: 10 },
  sectionTitleText: { fontSize: 18, fontWeight: "900", color: colors.text },
  linkText: { color: colors.accent, fontWeight: "800" },
  segment: { flexDirection: "row", backgroundColor: "#fff1a6", padding: 4, borderRadius: 10, marginBottom: 14, borderWidth: 1, borderColor: "#2f2f33" },
  segmentItem: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 12 },
  segmentItemActive: { backgroundColor: colors.accent },
  segmentText: { color: colors.muted, fontWeight: "700" },
  segmentTextActive: { color: colors.surface },
  amountInput: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 16,
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 14
  },
  formHint: { color: colors.muted, fontSize: 12, fontWeight: "700", marginTop: -8, marginBottom: 12 },
  fieldBlock: { marginBottom: 14 },
  label: { color: "#42455f", fontWeight: "800", marginBottom: 8 },
  input: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: colors.text
  },
  dateSelectButton: { backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12, paddingVertical: 12 },
  dateSelectText: { color: colors.text, fontSize: 16, fontWeight: "900" },
  dateSelectHint: { color: colors.muted, fontSize: 12, fontWeight: "700", marginTop: 3 },
  datePickerPanel: { backgroundColor: colors.surface, borderRadius: 16, padding: 12, marginTop: 10, borderWidth: 1, borderColor: colors.softBorder },
  datePickerHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  datePickerQuickText: { color: colors.text, fontWeight: "900", backgroundColor: colors.primarySoft, paddingHorizontal: 14, paddingVertical: 7, borderRadius: 999 },
  datePickerDoneText: { color: colors.text, fontWeight: "900", backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 7, borderRadius: 999 },
  datePickerSection: { marginBottom: 10 },
  datePickerTitle: { color: colors.muted, fontSize: 12, fontWeight: "800", marginBottom: 8 },
  datePickerGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  datePickerItem: { minWidth: 54, alignItems: "center", paddingHorizontal: 10, paddingVertical: 8, borderRadius: 999, backgroundColor: colors.accentSoft },
  datePickerItemActive: { backgroundColor: colors.primary },
  datePickerItemDisabled: { backgroundColor: "#f4f5f7" },
  datePickerItemText: { color: colors.text, fontWeight: "800" },
  datePickerItemTextActive: { color: colors.text },
  datePickerItemTextDisabled: { color: "#c5c8cf" },
  smallInput: {
    minWidth: 112,
    flex: 1
  },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { color: "#374151", fontWeight: "700" },
  chipTextActive: { color: colors.text },
  primaryButton: { backgroundColor: colors.primary, borderRadius: 16, alignItems: "center", paddingVertical: 15, marginTop: 4 },
  primaryButtonDisabled: { backgroundColor: "#e5e7eb" },
  pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  primaryButtonText: { color: colors.text, fontSize: 16, fontWeight: "900" },
  primaryButtonTextDisabled: { color: colors.muted },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primarySoft,
    borderRadius: 16,
    paddingVertical: 12,
    marginVertical: 12
  },
  disabledButton: { opacity: 0.55 },
  secondaryButtonText: { color: colors.text, fontWeight: "800" },
  row: { flexDirection: "row", gap: 8, alignItems: "center" },
  wrapRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, alignItems: "center" },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  iconButton: { backgroundColor: colors.surface, borderRadius: 16, padding: 12, borderWidth: 1, borderColor: colors.border },
  transactionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 12,
    marginBottom: 8,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: colors.softBorder
  },
  transactionIcon: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: "#f7f7f7" },
  transactionTitle: { color: colors.text, fontWeight: "800" },
  transactionMeta: { color: colors.muted, fontSize: 12, marginTop: 3 },
  transactionNote: { color: "#374151", fontSize: 12, marginTop: 3 },
  transactionRight: { alignItems: "flex-end", gap: 6 },
  transactionAmount: { color: colors.text, fontWeight: "500", fontSize: 17 },
  income: { color: colors.success },
  rowActions: { flexDirection: "row", gap: 10 },
  subtleText: { color: "#9ca3af", fontSize: 12, fontWeight: "700" },
  iconAction: { padding: 3 },
  progressBlock: { backgroundColor: colors.surface, borderRadius: 16, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.softBorder },
  progressTrack: { height: 8, borderRadius: 999, backgroundColor: colors.border, marginTop: 10, overflow: "hidden" },
  progressFill: { height: 8, borderRadius: 999, backgroundColor: colors.primary },
  statLine: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.softBorder,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10
  },
  statLabel: { color: colors.text, fontWeight: "700" },
  statValue: { color: "#374151", fontWeight: "700" },
  panelTitle: { color: colors.text, fontSize: 20, fontWeight: "900", marginBottom: 8 },
  textArea: {
    minHeight: 150,
    textAlignVertical: "top",
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    marginBottom: 12
  },
  uriText: { color: colors.muted, fontSize: 12, marginBottom: 10 },
  empty: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: colors.softBorder },
  emptyTitle: { color: colors.text, fontWeight: "800", marginBottom: 4 },
  noticeBox: { backgroundColor: colors.primarySoft, borderRadius: 16, padding: 14, borderWidth: 1, borderColor: "#ffe678", marginVertical: 12, gap: 8 },
  noticeTitle: { color: colors.text, fontSize: 15, fontWeight: "900" },
  mutedText: { color: colors.muted, lineHeight: 20 },
  tabBar: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
    paddingBottom: Platform.OS === "ios" ? 18 : 10
  },
  tabItem: { flex: 1, alignItems: "center", gap: 3 },
  centerTabItem: { marginTop: -30 },
  centerTabButton: {
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    borderWidth: 5,
    borderColor: colors.surface
  },
  tabText: { color: colors.muted, fontSize: 11, fontWeight: "700" },
  tabTextActive: { color: colors.text },
  chartCard: { backgroundColor: colors.surface, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: colors.softBorder, marginBottom: 12 },
  statsPage: { marginHorizontal: -16, marginTop: -16, paddingBottom: 18 },
  statsHero: { backgroundColor: colors.primary, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 16 },
  statsHeroToggle: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginBottom: 18 },
  statsHeroTitle: { color: colors.text, fontSize: 22, fontWeight: "900", textAlign: "center" },
  statsRangeSegment: { flexDirection: "row", borderWidth: 1, borderColor: colors.accent, borderRadius: 6, overflow: "hidden" },
  statsRangeItem: { flex: 1, textAlign: "center", paddingVertical: 10, color: "#6f6423", fontSize: 16, fontWeight: "900", borderRightWidth: 1, borderRightColor: colors.accent },
  statsRangeItemActive: { backgroundColor: colors.accent, color: colors.primary },
  statsPeriodRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 12, backgroundColor: colors.surface, paddingHorizontal: 20, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.softBorder },
  statsPeriodText: { color: colors.muted, fontSize: 16, fontWeight: "800" },
  statsPeriodTextActive: { color: colors.text, textDecorationLine: "underline", textDecorationColor: colors.text },
  flatTrendCard: { backgroundColor: colors.surface, paddingHorizontal: 20, paddingTop: 16, paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: colors.softBorder },
  trendMetaRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 8 },
  trendMetaText: { color: colors.muted, fontSize: 15, fontWeight: "700", marginBottom: 6 },
  trendMaxText: { color: colors.muted, fontSize: 14, fontWeight: "800", marginTop: 42 },
  simpleLinePlot: { height: 190, position: "relative", marginTop: 2 },
  statsRankingTitle: { backgroundColor: colors.surface, color: colors.text, fontSize: 22, fontWeight: "900", paddingHorizontal: 20, paddingTop: 18, paddingBottom: 12 },
  statsRankingList: { backgroundColor: colors.surface, paddingHorizontal: 20, paddingBottom: 24 },
  statsRankingRow: { flexDirection: "row", alignItems: "center", gap: 14, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.softBorder },
  statsRankingIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: "#f5f5f5", alignItems: "center", justifyContent: "center" },
  statsRankingContent: { flex: 1 },
  statsRankingTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  statsRankingName: { color: colors.text, fontSize: 17, fontWeight: "900" },
  statsRankingPercent: { color: colors.text, fontSize: 15, fontWeight: "600" },
  statsRankingAmount: { color: colors.text, fontSize: 16, fontWeight: "500" },
  statsRankingTrack: { height: 7, borderRadius: 999, backgroundColor: "#f0f0f0", marginTop: 8, overflow: "hidden" },
  statsRankingFill: { height: 7, borderRadius: 999, backgroundColor: colors.primary },
  donutWrap: { alignItems: "center", justifyContent: "center", marginVertical: 8 },
  donut: { width: 184, height: 184, alignItems: "center", justifyContent: "center" },
  donutTickWrap: { position: "absolute", width: 184, height: 184, alignItems: "center" },
  donutTick: { width: 8, height: 24, borderRadius: 999, marginTop: 4 },
  donutCenter: {
    width: 118,
    height: 118,
    borderRadius: 59,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.softBorder
  },
  donutLabel: { color: colors.muted, fontSize: 12, fontWeight: "800" },
  donutValue: { color: colors.text, fontSize: 22, fontWeight: "900", marginTop: 4 },
  legendRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, paddingVertical: 8 },
  legendLeft: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
  legendDot: { width: 10, height: 10, borderRadius: 5 },
  legendLabel: { color: colors.text, fontWeight: "800" },
  legendValue: { color: colors.muted, fontWeight: "800" },
  menuGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  menuTile: { width: "31%", alignItems: "center", backgroundColor: colors.surface, borderRadius: 14, paddingVertical: 16, borderWidth: 1, borderColor: colors.softBorder },
  menuIcon: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: colors.primarySoft, marginBottom: 8 },
  menuText: { color: colors.text, fontWeight: "800" },
  profileHero: { backgroundColor: colors.primary, marginHorizontal: -16, marginTop: -16, padding: 20, paddingBottom: 28 },
  profileName: { color: colors.text, fontSize: 24, fontWeight: "900", marginTop: 10 },
  profileStats: { flexDirection: "row", justifyContent: "space-around", marginTop: 22 },
  profileStatValue: { color: colors.text, fontSize: 24, fontWeight: "900", textAlign: "center" },
  profileStatLabel: { color: "#6f6423", fontWeight: "800", textAlign: "center", marginTop: 4 },
  rankingBarTrack: { height: 8, borderRadius: 999, backgroundColor: "#f0f0f0", marginTop: 8, overflow: "hidden" },
  rankingBarFill: { height: 8, borderRadius: 999, backgroundColor: colors.primary },
  receiptCandidateRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.softBorder },
  receiptCandidateCheck: { width: 26, alignItems: "center" },
  duplicateText: { color: colors.danger, fontSize: 12, marginTop: 4, fontWeight: "700" },
  warningText: { color: colors.warning, fontSize: 12, marginTop: 4, fontWeight: "700" },
  ocrSummaryRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 10, marginBottom: 4 },
  ocrSummaryText: { color: colors.text, fontSize: 12, fontWeight: "800" },
  settingRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.softBorder, gap: 12 },
  settingEditor: { marginTop: 14, gap: 10 },
  settingActionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
  inlineAddPanel: { backgroundColor: colors.surface, borderRadius: 16, padding: 12, marginBottom: 14, borderWidth: 1, borderColor: colors.softBorder }
  ,
  trendLegend: { flexDirection: "row", justifyContent: "flex-end", gap: 16, marginBottom: 10 },
  trendSelectedText: { color: colors.text, fontWeight: "900", marginBottom: 8 },
  lineChartWrap: { flexDirection: "row", minHeight: 210, gap: 8 },
  yAxis: { width: 58, justifyContent: "space-between", paddingTop: 8, paddingBottom: 30 },
  axisLabel: { color: colors.muted, fontSize: 10, fontWeight: "700", textAlign: "right" },
  linePlot: { flex: 1, height: 190, position: "relative", paddingBottom: 30 },
  gridLineTop: { position: "absolute", left: 0, right: 0, top: 8, height: 1, backgroundColor: colors.softBorder },
  gridLineMiddle: { position: "absolute", left: 0, right: 0, top: 82, height: 1, backgroundColor: colors.softBorder },
  gridLineBottom: { position: "absolute", left: 0, right: 0, bottom: 30, height: 1, backgroundColor: colors.softBorder },
  lineSeries: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0 },
  lineNodes: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0, flexDirection: "row" },
  linePointColumn: { flex: 1, alignItems: "center", justifyContent: "flex-end", position: "relative" },
  lineTapLayer: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0 },
  lineTapColumn: { position: "absolute", top: 0, bottom: 0, alignItems: "center", justifyContent: "flex-end" },
  lineNode: { position: "absolute", width: 12, height: 12, borderRadius: 6, borderWidth: 2, borderColor: colors.surface },
  singleLineNode: { position: "absolute", width: 11, height: 11, borderRadius: 6, borderWidth: 1, borderColor: "#3d3d42" },
  singleLineNodeActive: { borderWidth: 2, borderColor: colors.text },
  lineSegment: { position: "absolute", height: 3, borderRadius: 999 },
  trendLabel: { color: colors.muted, fontSize: 10, fontWeight: "700", marginTop: 8 }
});
